#!/bin/bash
#
# SkyView Universal Remote Access - SSH Configuration
# Configures SSH server with secure defaults and custom port
#

# Source dependencies
if [[ -z "${LIB_UTILS_SOURCED:-}" ]]; then
    local lib_dir
    lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    [[ -f "$lib_dir/utils.sh" ]] && source "$lib_dir/utils.sh"
fi

if [[ -z "${LIB_DETECT_OS_SOURCED:-}" ]]; then
    LIB_DETECT_OS_SOURCED=1
    local lib_dir
    lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    [[ -f "$lib_dir/detect_os.sh" ]] && source "$lib_dir/detect_os.sh"
fi

# ============================================================================
# Configuration Variables
# ============================================================================

SKYVIEW_SSH_PORT="${SKYVIEW_SSH_PORT:-2277}"
SKYVIEW_SSH_PASSWORD_AUTH="${SKYVIEW_SSH_PASSWORD_AUTH:-true}"
SKYVIEW_SSH_ROOT_LOGIN="${SKYVIEW_SSH_ROOT_LOGIN:-false}"
SKYVIEW_SSH_KEY_PATH="${SKYVIEW_SSH_KEY_PATH:-$HOME/.ssh/id_ed25519_skyview}"
SKYVIEW_SSH_X11_FORWARDING="${SKYVIEW_SSH_X11_FORWARDING:-true}"
SKYVIEW_SSH_AGENT_FORWARDING="${SKYVIEW_SSH_AGENT_FORWARDING:-true}"
SKYVIEW_SSH_KEEPALIVE="${SKYVIEW_SSH_KEEPALIVE:-60}"
SKYVIEW_SSH_MAX_AUTH_RETRIES="${SKYVIEW_SSH_MAX_AUTH_RETRIES:-3}"

# ============================================================================
# Installation Functions
# ============================================================================

# Install SSH server
install_openssh() {
    log_info "Installing OpenSSH server..."

    local packages
    packages=$(get_packages_for_method "openssh")

    if [[ -z "$packages" ]]; then
        log_error "Could not determine SSH packages for OS: $SKYVIEW_OS_NAME"
        return 1
    fi

    if ! install_packages "$packages"; then
        log_error "Failed to install SSH packages"
        return 1
    fi

    log_info "OpenSSH installed successfully"
    return 0
}

# Get package names for SSH based on OS
get_packages_for_method() {
    local method="$1"

    case "$SKYVIEW_PACKAGE_MANAGER" in
        apt)
            case "$method" in
                openssh) echo "openssh-server openssh-client";;
                *) echo "";;
            esac
            ;;
        dnf|yum)
            case "$method" in
                openssh) echo "openssh-server openssh-clients";;
                *) echo "";;
            esac
            ;;
        pacman)
            case "$method" in
                openssh) echo "openssh";;
                *) echo "";;
            esac
            ;;
        zypper)
            case "$method" in
                openssh) echo "openssh";;
                *) echo "";;
            esac
            ;;
        apk)
            case "$method" in
                openssh) echo "openssh-server openssh-client";;
                *) echo "";;
            esac
            ;;
        xbps)
            case "$method" in
                openssh) echo "openssh";;
                *) echo "";;
            esac
            ;;
        *)
            echo "openssh-server"
            ;;
    esac
}

# ============================================================================
# Configuration Functions
# ============================================================================

# Configure SSH server
configure_ssh() {
    log_info "Configuring SSH server on port $SKYVIEW_SSH_PORT..."

    require_root || return 1

    local sshd_config="/etc/ssh/sshd_config"
    local sshd_config_d="/etc/ssh/sshd_config.d"

    # Check if SSH is installed
    if [[ ! -f "$sshd_config" ]]; then
        if ! install_openssh; then
            log_error "SSH not installed and could not be installed"
            return 1
        fi
    fi

    # Create config.d directory if it doesn't exist
    mkdir -p "$sshd_config_d" 2>/dev/null || true

    # Backup existing configuration
    backup_file "$sshd_config"

    # Apply configuration
    configure_sshd_config
    configure_sshd_config_d
    configure_firewall_for_ssh

    # Generate host keys if missing
    generate_ssh_host_keys

    # Set permissions
    set_ssh_permissions

    log_info "SSH configuration complete"
    return 0
}

# Configure main sshd_config
configure_sshd_config() {
    local sshd_config="/etc/ssh/sshd_config"

    # Create a custom configuration that preserves existing settings
    local custom_config="/etc/ssh/sshd_config.d/skyview-custom.conf"

    cat > "$custom_config" << EOF
# SkyView Universal Remote Access - SSH Configuration
# Generated by skyview-remote-access
# DO NOT EDIT - Changes will be preserved

# Port configuration
Port $SKYVIEW_SSH_PORT

# Authentication settings
PasswordAuthentication $SKYVIEW_SSH_PASSWORD_AUTH
PermitRootLogin $SKYVIEW_SSH_ROOT_LOGIN
MaxAuthTries $SKYVIEW_SSH_MAX_AUTH_RETRIES

# Connection settings
TCPKeepAlive $SKYVIEW_SSH_KEEPALIVE
ClientAliveInterval 60
ClientAliveCountMax 3

# X11 and Agent forwarding
X11Forwarding $SKYVIEW_SSH_X11_FORWARDING
ForwardAgent $SKYVIEW_SSH_AGENT_FORWARDING

# Security hardening
IgnoreRhosts yes
StrictModes yes
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys

# Protocol and algorithms
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Logging
SyslogFacility AUTH
LogLevel INFO

# Subsystems
Subsystem sftp /usr/lib/openssh/sftp-server

# Allow client-specific configurations
Include /etc/ssh/sshd_config.d/*.conf
EOF

    log_debug "Created SSH custom configuration"
}

# Configure additional security settings
configure_sshd_config_d() {
    local security_config="/etc/ssh/sshd_config.d/skyview-security.conf"

    cat > "$security_config" << 'EOF'
# SkyView SSH Security Hardening
# Additional security settings

# Disable weak ciphers and algorithms
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
KexAlgorithms curve25519-sha256,ecdh-sha2-nistp521

# Rate limiting
MaxStartups 10:30:100
MaxSessions 10

# Banner
Banner /etc/issue.net

# Disable tunneling and forwarding (if not needed)
AllowTcpForwarding yes
PermitTunnel yes

# X11 display offset
X11DisplayOffset 10
EOF

    log_debug "Created SSH security configuration"
}

# Generate SSH host keys if they don't exist
generate_ssh_host_keys() {
    log_info "Checking SSH host keys..."

    local key_types=("rsa" "ecdsa" "ed25519")
    local generated=0

    for key_type in "${key_types[@]}"; do
        local key_file="/etc/ssh/ssh_host_${key_type}_key"
        if [[ ! -f "$key_file" ]]; then
            log_info "Generating ${key_type^^} host key..."
            ssh-keygen -t "$key_type" -f "$key_file" -N "" -C "root@$(hostname)" 2>/dev/null
            ((generated++))
        fi
    done

    if [[ $generated -gt 0 ]]; then
        log_info "Generated $generated new host key(s)"
    else
        log_debug "All host keys already exist"
    fi
}

# Set proper permissions on SSH files
set_ssh_permissions() {
    # Set permissions on host keys (restrictive)
    chmod 600 /etc/ssh/ssh_host_*_key 2>/dev/null || true
    chmod 644 /etc/ssh/ssh_host_*_key.pub 2>/dev/null || true

    # Set permissions on configuration
    chmod 644 /etc/ssh/sshd_config 2>/dev/null || true
    chmod 644 /etc/ssh/sshd_config.d/*.conf 2>/dev/null || true

    log_debug "Set SSH file permissions"
}

# Configure firewall for SSH
configure_firewall_for_ssh() {
    log_info "Configuring firewall for SSH on port $SKYVIEW_SSH_PORT..."

    local firewall_script="/usr/local/bin/skyview-ssh-firewall.sh"

    # Create firewall script
    cat > "$firewall_script" << EOF
#!/bin/bash
# SkyView SSH Firewall Configuration
# Generated by skyview-remote-access

SKYVIEW_SSH_PORT=${SKYVIEW_SSH_PORT}

# Allow SSH port
case "\$(detect_firewall 2>/dev/null)" in
    ufw)
        ufw allow \$SKYVIEW_SSH_PORT/tcp comment 'SkyView SSH' 2>/dev/null || true
        ;;
    firewalld)
        firewall-cmd --permanent --add-port=\$SKYVIEW_SSH_PORT/tcp 2>/dev/null || true
        firewall-cmd --reload 2>/dev/null || true
        ;;
    iptables)
        iptables -C INPUT -p tcp --dport \$SKYVIEW_SSH_PORT -j ACCEPT 2>/dev/null || \
        iptables -I INPUT -p tcp --dport \$SKYVIEW_SSH_PORT -j ACCEPT 2>/dev/null || true
        ;;
    nftables)
        nft add rule inet filter input tcp dport \$SKYVIEW_SSH_PORT accept 2>/dev/null || true
        ;;
esac
EOF

    chmod +x "$firewall_script"

    # Execute firewall configuration
    "$firewall_script" 2>/dev/null || log_warn "Firewall configuration failed or not available"

    log_info "Firewall configured for SSH port $SKYVIEW_SSH_PORT"
}

# ============================================================================
# SSH Key Management
# ============================================================================

# Generate or get SkyView SSH key
setup_skyview_ssh_key() {
    log_info "Setting up SkyView SSH key..."

    local key_path="$SKYVIEW_SSH_KEY_PATH"
    local key_dir
    key_dir=$(dirname "$key_path")

    # Create .ssh directory
    mkdir -p "$key_dir"
    chmod 700 "$key_dir"

    # Check for existing key
    if [[ -f "$key_path" ]]; then
        log_info "Using existing SkyView SSH key: $key_path"
    else
        log_info "Generating new ED25519 SSH key..."
        ssh-keygen -t ed25519 -f "$key_path" -N "" -C "SkyView Remote Access - $(whoami)@$(hostname)" 2>/dev/null

        if [[ $? -eq 0 && -f "$key_path" ]]; then
            log_info "Generated new SSH key: $key_path"
        else
            log_error "Failed to generate SSH key"
            return 1
        fi
    fi

    # Set proper permissions
    chmod 600 "$key_path"
    chmod 644 "${key_path}.pub"

    # Export key path
    export SKYVIEW_SSH_KEY_PATH="$key_path"

    log_info "SkyView SSH key ready at: $key_path"
    return 0
}

# Deploy SSH key to remote host
deploy_ssh_key_to_remote() {
    local remote_host="$1"
    local remote_user="$2"
    local remote_port="${3:-22}"

    if [[ -z "$remote_host" || -z "$remote_user" ]]; then
        log_error "Remote host and user are required"
        return 1
    fi

    log_info "Deploying SSH key to ${remote_user}@${remote_host}:${remote_port}..."

    # Ensure key exists
    if [[ ! -f "$SKYVIEW_SSH_KEY_PATH" ]]; then
        setup_skyview_ssh_key || return 1
    fi

    # Use ssh-copy-id if available
    if command -v ssh-copy-id &>/dev/null; then
        if ssh-copy-id -i "${SKYVIEW_SSH_KEY_PATH}.pub" -p "$remote_port" "${remote_user}@${remote_host}" 2>/dev/null; then
            log_info "SSH key deployed successfully via ssh-copy-id"
            return 0
        fi
    fi

    # Manual deployment as fallback
    log_warn "ssh-copy-id not available, using manual deployment..."

    # Copy public key to remote
    local pub_key
    pub_key=$(cat "${SKYVIEW_SSH_KEY_PATH}.pub")

    if ssh -p "$remote_port" "${remote_user}@${remote_host}" "mkdir -p ~/.ssh && chmod 700 ~/.ssh && echo '${pub_key}' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys" 2>/dev/null; then
        log_info "SSH key deployed manually"
        return 0
    fi

    log_error "Failed to deploy SSH key to remote host"
    return 1
}

# ============================================================================
# Service Management Functions
# ============================================================================

# Start SSH service
start_ssh() {
    log_info "Starting SSH service..."

    if ! command -v systemctl &>/dev/null; then
        log_error "systemctl not available"
        return 1
    fi

    # Try both service names
    systemctl start sshd 2>/dev/null || systemctl start ssh 2>/dev/null || {
        log_error "Failed to start SSH service"
        return 1
    }

    sleep 1

    # Verify service is running
    if systemctl is-active --quiet sshd 2>/dev/null || systemctl is-active --quiet ssh 2>/dev/null; then
        log_info "SSH service started successfully"
        return 0
    else
        log_error "SSH service failed to start"
        journalctl -u sshd --no-pager -n 20 2>/dev/null || true
        return 1
    fi
}

# Stop SSH service
stop_ssh() {
    log_info "Stopping SSH service..."

    if command -v systemctl &>/dev/null; then
        systemctl stop sshd 2>/dev/null || systemctl stop ssh 2>/dev/null || true
    fi

    log_info "SSH service stopped"
}

# Enable SSH on boot
enable_ssh() {
    log_info "Enabling SSH on boot..."

    if command -v systemctl &>/dev/null; then
        systemctl enable sshd 2>/dev/null || systemctl enable ssh 2>/dev/null || true
    fi
}

# Disable SSH on boot
disable_ssh() {
    log_info "Disabling SSH on boot..."

    if command -v systemctl &>/dev/null; then
        systemctl disable sshd 2>/dev/null || systemctl disable ssh 2>/dev/null || true
    fi
}

# Restart SSH service
restart_ssh() {
    log_info "Restarting SSH service..."

    if command -v systemctl &>/dev/null; then
        systemctl restart sshd 2>/dev/null || systemctl restart ssh 2>/dev/null || {
            log_error "Failed to restart SSH service"
            return 1
        }
    fi

    log_info "SSH service restarted"
    return 0
}

# ============================================================================
# Verification Functions
# ============================================================================

# Verify SSH configuration
verify_ssh() {
    log_info "Verifying SSH configuration..."

    local errors=0

    # Check if SSH is installed
    if ! command -v sshd &>/dev/null; then
        log_error "SSH server is not installed"
        ((errors++))
    fi

    # Check configuration file
    if [[ ! -f /etc/ssh/sshd_config ]]; then
        log_error "sshd_config is missing"
        ((errors++))
    fi

    # Check port is configured
    if ! grep -q "^Port $SKYVIEW_SSH_PORT" /etc/ssh/sshd_config /etc/ssh/sshd_config.d/*.conf 2>/dev/null; then
        log_warn "SSH port $SKYVIEW_SSH_PORT not configured"
    fi

    # Check port is listening
    if is_port_open "localhost" "$SKYVIEW_SSH_PORT"; then
        log_info "SSH port $SKYVIEW_SSH_PORT is listening"
    else
        log_warn "SSH port $SKYVIEW_SSH_PORT is not listening"
        ((errors++))
    fi

    # Check service status
    if command -v systemctl &>/dev/null; then
        if systemctl is-active --quiet sshd 2>/dev/null || systemctl is-active --quiet ssh 2>/dev/null; then
            log_info "SSH service is active"
        else
            log_warn "SSH service is not active"
            ((errors++))
        fi
    fi

    return $errors
}

# Get SSH status
get_ssh_status() {
    local status="unknown"
    local port_status="closed"

    if is_port_open "localhost" "$SKYVIEW_SSH_PORT"; then
        port_status="open"
    fi

    if command -v systemctl &>/dev/null; then
        if systemctl is-active --quiet sshd 2>/dev/null || systemctl is-active --quiet ssh 2>/dev/null; then
            status="active"
        else
            status="inactive"
        fi
    fi

    echo "Status: $status, Port: $port_status"
}

# ============================================================================
# Utility Functions
# ============================================================================

# Print SSH configuration summary
print_ssh_summary() {
    print_header "SSH Configuration"

    cat << EOF
SSH Port:           $SKYVIEW_SSH_PORT
Password Auth:      $SKYVIEW_SSH_PASSWORD_AUTH
Root Login:         $SKYVIEW_SSH_ROOT_LOGIN
X11 Forwarding:     $SKYVIEW_SSH_X11_FORWARDING
Key Path:           $SKYVIEW_SSH_KEY_PATH

Configuration:      $([[ -f /etc/ssh/sshd_config ]] && echo "configured" || echo "missing")
$(get_ssh_status)
EOF
}

# Test SSH connection
test_ssh_connection() {
    local host="${1:-localhost}"
    local port="${2:-$SKYVIEW_SSH_PORT}"
    local user="${3:-$(whoami)}"

    log_info "Testing SSH connection to ${user}@${host}:${port}..."

    if ssh -p "$port" -o BatchMode=yes -o ConnectTimeout=5 "$user@$host" "echo 'SSH connection successful'" 2>/dev/null; then
        log_info "SSH connection test passed"
        return 0
    else
        log_error "SSH connection test failed"
        return 1
    fi
}

# ============================================================================
# Bridge API Functions (for frontend integration)
# ============================================================================

# Get SSH status as JSON
get_ssh_status_json() {
    local status port running key_exists

    status="unknown"
    port=$SKYVIEW_SSH_PORT
    running="false"
    key_exists="false"

    if is_port_open "localhost" "$port"; then
        port_status="open"
    fi

    if command -v systemctl &>/dev/null; then
        if systemctl is-active --quiet sshd 2>/dev/null || systemctl is-active --quiet ssh 2>/dev/null; then
            status="active"
            running="true"
        else
            status="inactive"
        fi
    fi

    [[ -f "$SKYVIEW_SSH_KEY_PATH" ]] && key_exists="true"

    cat << EOF
{
  "service": "ssh",
  "status": "$status",
  "port": $port,
  "running": $running,
  "passwordAuth": $SKYVIEW_SSH_PASSWORD_AUTH,
  "rootLogin": $SKYVIEW_SSH_ROOT_LOGIN,
  "keyPath": "$SKYVIEW_SSH_KEY_PATH",
  "keyExists": $key_exists,
  "x11Forwarding": $SKYVIEW_SSH_X11_FORWARDING
}
EOF
}
