#!/bin/bash
#
# SkyView Universal Remote Access - RDP Configuration
# Configures xrdp, native Wayland RDP (KRdp, gnome-remote-desktop)
#

# Source dependencies
if [[ -z "${LIB_DETECT_OS_SOURCED:-}" ]]; then
    local lib_dir
    lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    [[ -f "$lib_dir/detect_os.sh" ]] && source "$lib_dir/detect_os.sh"
fi

if [[ -z "${LIB_DETECT_DE_SOURCED:-}" ]]; then
    LIB_DETECT_DE_SOURCED=1
    local lib_dir
    lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    [[ -f "$lib_dir/detect_de.sh" ]] && source "$lib_dir/detect_de.sh"
fi

# ============================================================================
# Configuration Variables
# ============================================================================

SKYVIEW_RDP_PORT="${SKYVIEW_RDP_PORT:-3389}"
SKYVIEW_RDP_SESMAN_PORT="${SKYVIEW_RDP_SESMAN_PORT:-3350}"
SKYVIEW_RDP_SSL_ENABLED="${SKYVIEW_RDP_SSL_ENABLED:-true}"
SKYVIEW_RDP_MAX_BPP="${SKYVIEW_RDP_MAX_BPP:-24}"
SKYVIEW_RDP_SECURITY_LAYER="${SKYVIEW_RDP_SECURITY_LAYER:-rdp}"

# ============================================================================
# Installation Functions
# ============================================================================

# Install xrdp and dependencies
install_xrdp() {
    log_info "Installing xrdp..."

    local packages
    packages=$(get_packages_for_method "xrdp")

    if [[ -z "$packages" ]]; then
        log_error "Could not determine xrdp packages for OS: $SKYVIEW_OS_NAME"
        return 1
    fi

    # Install packages
    if ! install_packages $packages; then
        log_error "Failed to install xrdp packages"
        return 1
    fi

    # Install additional dependencies
    case "$SKYVIEW_PACKAGE_MANAGER" in
        apt)
            install_packages "xorgxrdp" || log_warn "xorgxrdp installation failed"
            ;;
        dnf|yum)
            # xorg-x11-server-Xorg is usually a dependency
            ;;
        pacman)
            # xorg-server is usually installed
            ;;
    esac

    log_info "xrdp installed successfully"
    return 0
}

# Install native Wayland RDP
install_native_rdp() {
    local method="$1"
    log_info "Installing native Wayland RDP: $method"

    case "$method" in
        krdp|krfb)
            local packages
            packages=$(get_packages_for_method "krdp")
            install_packages $packages
            ;;
        gnome-remote-desktop)
            local packages
            packages=$(get_packages_for_method "gnome-remote-desktop")
            install_packages $packages
            ;;
    esac
}

# ============================================================================
# Configuration Functions
# ============================================================================

# Configure xrdp
configure_xrdp() {
    log_info "Configuring xrdp..."

    require_root || return 1

    # Backup existing configuration
    backup_file "/etc/xrdp/xrdp.ini"
    backup_file "/etc/xrdp/sesman.ini"

    # Generate SSL certificates
    if [[ "$SKYVIEW_RDP_SSL_ENABLED" == "true" ]]; then
        generate_xrdp_certificates || log_warn "Failed to generate certificates"
    fi

    # Configure xrdp.ini
    configure_xrdp_ini

    # Configure sesman.ini
    configure_sesman_ini

    # Configure startwm.sh for DE support
    configure_startwm_script

    # Set permissions
    chmod_xrdp_config

    fix_rdp_permissions

    log_info "xrdp configuration complete"
    return 0
}

# Generate self-signed SSL certificates for xrdp
generate_xrdp_certificates() {
    log_info "Generating xrdp SSL certificates..."

    local cert_file="/etc/xrdp/cert.pem"
    local key_file="/etc/xrdp/key.pem"

    if [[ -f "$cert_file" && -f "$key_file" ]]; then
        log_debug "Certificates already exist, skipping generation"
        return 0
    fi

    if ! command -v openssl &>/dev/null; then
        install_package "openssl" || return 1
    fi

    openssl req -x509 -newkey rsa:2048 -nodes \
        -keyout "$key_file" -out "$cert_file" \
        -days 3650 \
        -subj "/C=US/ST=State/L=City/O=Organization/CN=$(hostname)" \
        2>/dev/null

    if [[ $? -eq 0 ]]; then
        chmod 600 "$key_file"
        chmod 644 "$cert_file"
        chown root:root "$key_file" "$cert_file"
        log_info "SSL certificates generated successfully"
        return 0
    else
        log_error "Failed to generate SSL certificates"
        return 1
    fi
}

# Configure xrdp.ini
configure_xrdp_ini() {
    local xrdp_ini="/etc/xrdp/xrdp.ini"

    cat > "$xrdp_ini" << 'EOF'
; SkyView Universal Remote Access - xrdp configuration
; Generated by skyview-remote-access
; DO NOT EDIT MANUALLY - changes will be overwritten

[Globals]
; Network settings
port=3389
bind_address=0.0.0.0

; Security settings
security_layer=${SKYVIEW_RDP_SECURITY_LAYER:-rdp}
crypt_level=high
ssl_protocols=TLSv1.2,TLSv1.3
certificate=/etc/xrdp/cert.pem
key_file=/etc/xrdp/key.pem

; Display settings
max_bpp=24
bitmap_cache=true
bitmap_compression=true
bulk_compression=true

; Connection settings
tcp_keepalive=true
tcp_nodelay=true

; User interface
fork_on_port_available=false

[Logging]
LogFile=/var/log/xrdp.log
LogLevel=INFO
EnableSyslog=true
SyslogLevel=INFO

[Channels]
rdpdr=true
rdpsnd=true
cliprdr=true
rail=true
drdynvc=true

[Xorg]
name=Xorg
lib=libxup.so
username=ask
password=ask
ip=127.0.0.1
port=-1
code=20

[xvnc]
name=Xvnc
lib=libvnc.so
username=ask
password=ask
ip=127.0.0.1
port=-1

[console]
name=console
lib=libvnc.so
username=ask
password=ask
ip=127.0.0.1
port=5900

EOF

    # Apply DE-specific settings
    apply_de_specific_xrdp_settings "$xrdp_ini"

    log_debug "Configured xrdp.ini"
}

# Apply DE-specific settings to xrdp.ini
apply_de_specific_xrdp_settings() {
    local xrdp_ini="$1"
    local de_lower
    de_lower=$(lowercase "$SKYVIEW_DE")

    # Add color depth recommendation based on DE
    case "$de_lower" in
        *"kde"*|*"plasma"*)
            # KDE works well with 32-bit color
            sed -i 's/max_bpp=24/max_bpp=32/' "$xrdp_ini"
            ;;
        *"xfce"*)
            # XFCE works well with 24-bit
            sed -i 's/max_bpp=24/max_bpp=24/' "$xrdp_ini"
            ;;
        *"gnome"*)
            # GNOME may need 24-bit for better performance
            sed -i 's/max_bpp=24/max_bpp=24/' "$xrdp_ini"
            ;;
    esac
}

# Configure sesman.ini
configure_sesman_ini() {
    local sesman_ini="/etc/xrdp/sesman.ini"

    cat > "$sesman_ini" << EOF
; SkyView Universal Remote Access - sesman configuration
; Generated by skyview-remote-access

[Globals]
ListenAddress=0.0.0.0
ListenPort=3350
EnableUserWindowManager=true
UserWindowManager=startwm.sh
DefaultWindowManager=startwm.sh
ReconnectScript=reconnectwm.sh

[Security]
AllowRootLogin=false
MaxLoginRetry=3
TerminalServerUsers=remotedesktop
RestrictOutboundClipboard=true
AlwaysGroupCheck=true

[Sessions]
X11DisplayOffset=10
MaxSessions=50
KillDisconnected=true
DisconnectedTimeLimit=3600
IdleTimeLimit=0
Policy=Default

[Xorg]
param=/usr/bin/Xorg
param=-nolisten
param=tcp

EOF

    log_debug "Configured sesman.ini"
}

# Configure startwm.sh for multi-DE support
configure_startwm_script() {
    local startwm="/etc/xrdp/startwm.sh"

    cat > "$startwm" << 'EOFSCRIPT'
#!/bin/sh
# SkyView Universal Remote Access - Session Startup Script
# Generated by skyview-remote-access

# Clean up any stale files
rm -f /tmp/.X11-unix/X* 2>/dev/null
rm -f ~/.ICEauthority 2>/dev/null

# Detect and start appropriate desktop environment
start_desktop() {
    local de_path=""

    # Check for installed desktop environments in order of preference
    if [[ -x "/usr/bin/gnome-session" ]]; then
        de_path="/usr/bin/gnome-session"
        export GNOME_SHELL_SESSION_MODE=gnome
        export XDG_CURRENT_DESKTOP=GNOME
    elif [[ -x "/usr/bin/startplasma-x11" ]]; then
        de_path="/usr/bin/startplasma-x11"
        export XDG_CURRENT_DESKTOP=KDE
    elif [[ -x "/usr/bin/xfce4-session" ]]; then
        de_path="/usr/bin/xfce4-session"
        export XDG_CURRENT_DESKTOP=XFCE
    elif [[ -x "/usr/bin/cinnamon-session" ]]; then
        de_path="/usr/bin/cinnamon-session"
        export XDG_CURRENT_DESKTOP=Cinnamon
    elif [[ -x "/usr/bin/mate-session" ]]; then
        de_path="/usr/bin/mate-session"
        export XDG_CURRENT_DESKTOP=MATE
    elif [[ -x "/usr/bin/lxqt-session" ]]; then
        de_path="/usr/bin/lxqt-session"
        export XDG_CURRENT_DESKTOP=LXQt
    elif [[ -x "/usr/bin/lxsession" ]]; then
        de_path="/usr/bin/lxsession"
        export XDG_CURRENT_DESKTOP=LXDE
    else
        # Fallback to XFCE if available, otherwise try default X session
        if [[ -x "/usr/bin/xfce4-session" ]]; then
            de_path="/usr/bin/xfce4-session"
            export XDG_CURRENT_DESKTOP=XFCE
        elif [[ -f "/usr/share/xsessions/default.desktop" ]]; then
            local session
            session=$(grep -oP 'Exec=\K.*' /usr/share/xsessions/default.desktop | head -1)
            if [[ -n "$session" ]]; then
                de_path="$session"
            fi
        else
            # Last resort: try to find any .desktop file
            local desktop_file
            desktop_file=$(ls /usr/share/xsessions/*.desktop 2>/dev/null | head -1)
            if [[ -n "$desktop_file" ]]; then
                de_path=$(grep -oP 'Exec=\K.*' "$desktop_file" | head -1)
            fi
        fi
    fi

    if [[ -n "$de_path" && -x "$de_path" ]]; then
        echo "Starting desktop: $de_path"
        exec "$de_path"
    else
        echo "ERROR: No desktop environment found"
        exit 1
    fi
}

# Check if we're in a remote session and start desktop
if [[ -z "$DESKTOP_SESSION_STARTED" ]]; then
    export DESKTOP_SESSION_STARTED=1
    start_desktop
fi
EOFSCRIPT

    chmod +x "$startwm"
    log_debug "Configured startwm.sh"
}

# Set proper permissions on xrdp configuration
chmod_xrdp_config() {
    chown root:root /etc/xrdp/xrdp.ini /etc/xrdp/sesman.ini 2>/dev/null || true
    chmod 644 /etc/xrdp/xrdp.ini /etc/xrdp/sesman.ini 2>/dev/null || true
    chmod 600 /etc/xrdp/key.pem 2>/dev/null || true
    chmod 644 /etc/xrdp/cert.pem 2>/dev/null || true
}

fix_rdp_permissions() {
    log_info "Applying RDP permission fixes..."

    if getent group ssl-cert >/dev/null; then
        usermod -a -G ssl-cert xrdp 2>/dev/null || true
    fi

    if [[ -f "/etc/ssl/private/ssl-cert-snakeoil.key" ]]; then
        chown xrdp:xrdp /etc/ssl/certs/ssl-cert-snakeoil.pem 2>/dev/null || true
        chown xrdp:xrdp /etc/ssl/private/ssl-cert-snakeoil.key 2>/dev/null || true
        chmod 640 /etc/ssl/private/ssl-cert-snakeoil.key 2>/dev/null || true
    fi

    rm -rf /run/xrdp/sockdir/* 2>/dev/null || true
}

# ============================================================================
# Native Wayland RDP Configuration
# ============================================================================

# Configure KDE KRdp
configure_krdp() {
    log_info "Configuring KDE KRdp..."

    require_root || return 1

    # Create user service directory
    mkdir -p ~/.config/systemd/user 2>/dev/null || sudo -u "$USER" mkdir -p ~/.config/systemd/user

    # Create systemd user service
    local service_file
    if [[ -n "$SUDO_USER" ]]; then
        service_file="/home/$SUDO_USER/.config/systemd/user/skyview-kde-rdp.service"
    else
        service_file="$HOME/.config/systemd/user/skyview-kde-rdp.service"
    fi

    mkdir -p "$(dirname "$service_file")"

    cat > "$service_file" << EOF
[Unit]
Description=SkyView KDE RDP Service
After=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/bin/krfb --port 5900
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF

    if command -v systemctl &>/dev/null; then
        systemctl --user daemon-reload 2>/dev/null || true
        systemctl --user enable skyview-kde-rdp.service 2>/dev/null || true
        systemctl --user start skyview-kde-rdp.service 2>/dev/null || true
    fi

    log_info "KDE KRdp configured"
    return 0
}

# Configure GNOME remote desktop
configure_gnome_remote_desktop() {
    log_info "Configuring GNOME Remote Desktop..."

    require_root || return 1

    # Install and enable gnome-remote-desktop
    local packages
    packages=$(get_packages_for_method "gnome-remote-desktop")
    install_packages $packages || return 1

    # Enable via dconf/GSettings
    if command -v gsettings &>/dev/null; then
        gsettings set org.gnome.desktop.remote-desktop.rdp enable true 2>/dev/null || true
        gsettings set org.gnome.desktop.remote-desktop.rdp port 3389 2>/dev/null || true
    fi

    # Create systemd service
    local service_file="/etc/systemd/system/skyview-gnome-rdp.service"

    cat > "$service_file" << EOF
[Unit]
Description=SkyView GNOME Remote Desktop
After=graphical-session.target
Wants=graphical-session.target

[Service]
Type=dbus
BusName=org.gnome.RemoteDesktop
ExecStart=/usr/libexec/gnome-remote-desktop-daemon
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

    if command -v systemctl &>/dev/null; then
        systemctl daemon-reload
        systemctl enable --now gnome-remote-desktop.service 2>/dev/null || true
    fi

    log_info "GNOME Remote Desktop configured"
    return 0
}

# ============================================================================
# Service Management Functions
# ============================================================================

# Reclaim RDP port
reclaim_rdp_port() {
    local port="${1:-3389}"
    
    log_info "Attempting to reclaim RDP port $port..."
    
    local pid
    pid=$(lsof -t -i :"$port" 2>/dev/null)
    if [[ -n "$pid" ]]; then
        log_warn "Found process $pid listening on port $port. Terminating..."
        kill -9 "$pid" 2>/dev/null || true
    fi
    
    # Clean up stale pid files
    rm -f /var/run/xrdp.pid 2>/dev/null
    rm -f /var/run/xrdp/xrdp.pid 2>/dev/null
    rm -f /run/xrdp/xrdp.pid 2>/dev/null
}

# Start xrdp services
start_xrdp() {
    log_info "Starting xrdp services..."

    if ! command -v systemctl &>/dev/null; then
        log_error "systemctl not available"
        return 1
    fi

    # Reclaim port
    reclaim_rdp_port "$SKYVIEW_RDP_PORT"

    # Start sesman first
    systemctl start xrdp-sesman.service 2>/dev/null || true
    systemctl start xrdp-sesman.socket 2>/dev/null || true

    # Start xrdp
    systemctl start xrdp.service 2>/dev/null || true

    # Verify services are running
    sleep 2

    if systemctl is-active --quiet xrdp.service; then
        log_info "xrdp service started successfully"
        return 0
    else
        log_error "xrdp service failed to start"
        journalctl -u xrdp --no-pager -n 20
        return 1
    fi
}

# Stop xrdp services
stop_xrdp() {
    log_info "Stopping xrdp services..."

    if command -v systemctl &>/dev/null; then
        systemctl stop xrdp.service 2>/dev/null || true
        systemctl stop xrdp-sesman.service 2>/dev/null || true
        systemctl stop xrdp-sesman.socket 2>/dev/null || true
    fi

    log_info "xrdp services stopped"
}

# Enable xrdp on boot
enable_xrdp() {
    log_info "Enabling xrdp on boot..."

    if command -v systemctl &>/dev/null; then
        systemctl enable xrdp.service 2>/dev/null || true
        systemctl enable xrdp-sesman.service 2>/dev/null || true
        systemctl enable xrdp-sesman.socket 2>/dev/null || true
    fi
}

# Disable xrdp on boot
disable_xrdp() {
    log_info "Disabling xrdp on boot..."

    if command -v systemctl &>/dev/null; then
        systemctl disable xrdp.service 2>/dev/null || true
        systemctl disable xrdp-sesman.service 2>/dev/null || true
        systemctl disable xrdp-sesman.socket 2>/dev/null || true
    fi
}

# ============================================================================
# Verification Functions
# ============================================================================

# Verify xrdp configuration
verify_xrdp() {
    log_info "Verifying xrdp configuration..."

    local errors=0

    # Check if xrdp is installed
    if ! command -v xrdp &>/dev/null; then
        log_error "xrdp is not installed"
        ((errors++))
    fi

    # Check configuration files
    if [[ ! -f /etc/xrdp/xrdp.ini ]]; then
        log_error "xrdp.ini is missing"
        ((errors++))
    fi

    if [[ ! -f /etc/xrdp/sesman.ini ]]; then
        log_error "sesman.ini is missing"
        ((errors++))
    fi

    # Check port is listening
    if is_port_open "localhost" 3389; then
        log_info "RDP port 3389 is listening"
    else
        log_warn "RDP port 3389 is not listening"
    fi

    # Check service status
    if command -v systemctl &>/dev/null; then
        if systemctl is-active --quiet xrdp.service; then
            log_info "xrdp service is active"
        else
            log_warn "xrdp service is not active"
            ((errors++))
        fi
    fi

    return $errors
}

# ============================================================================
# Utility Functions
# ============================================================================

# Backup a configuration file
backup_file() {
    local file="$1"
    if [[ -f "$file" ]]; then
        cp "$file" "${file}.backup.$(date +%Y%m%d%H%M%S)" 2>/dev/null || true
    fi
}

# Get RDP status
get_rdp_status() {
    local status="unknown"
    local port_status="closed"

    if is_port_open "localhost" 3389; then
        port_status="open"
    fi

    if command -v systemctl &>/dev/null; then
        if systemctl is-active --quiet xrdp.service; then
            status="active"
        elif systemctl is-active --quiet xrdp-sesman.service; then
            status="sesman_only"
        else
            status="inactive"
        fi
    fi

    echo "Status: $status, Port: $port_status"
}

# Print RDP configuration summary
print_rdp_summary() {
    print_header "RDP Configuration"

    cat << EOF
RDP Port:         $SKYVIEW_RDP_PORT
Security Layer:   $SKYVIEW_RDP_SECURITY_LAYER
SSL Enabled:      $SKYVIEW_RDP_SSL_ENABLED
Max Color Depth:  $SKYVIEW_RDP_MAX_BPP
 Sesman Port:     $SKYVIEW_RDP_SESMAN_PORT

Configuration:    $([[ -f /etc/xrdp/xrdp.ini ]] && echo "configured" || echo "missing")
Certificate:      $([[ -f /etc/xrdp/cert.pem ]] && echo "present" || echo "missing")
$(get_rdp_status)
EOF
}
