#!/bin/bash
#
# SkyView Universal Remote Access - VNC Configuration
# Configures TigerVNC server with security and optimization settings
#

# Source dependencies
if [[ -z "${LIB_DETECT_OS_SOURCED:-}" ]]; then
    local lib_dir
    lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    [[ -f "$lib_dir/detect_os.sh" ]] && source "$lib_dir/detect_os.sh"
fi

if [[ -z "${LIB_DETECT_DE_SOURCED:-}" ]]; then
    LIB_DETECT_DE_SOURCED=1
    local lib_dir
    lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    [[ -f "$lib_dir/detect_de.sh" ]] && source "$lib_dir/detect_de.sh"
fi

# ============================================================================
# Configuration Variables
# ============================================================================

SKYVIEW_VNC_PORT="${SKYVIEW_VNC_PORT:-5900}"
SKYVIEW_VNC_DISPLAY="${SKYVIEW_VNC_DISPLAY:-:0}"
SKYVIEW_VNC_GEOMETRY="${SKYVIEW_VNC_GEOMETRY:-1920x1080}"
SKYVIEW_VNC_DEPTH="${SKYVIEW_VNC_DEPTH:-24}"
SKYVIEW_VNC_PASSWORD_FILE=""
SKYVIEW_VNC_SECURITY_TYPE="${SKYVIEW_VNC_SECURITY_TYPE:-TLSVnc}"
SKYVIEW_VNC_ALWAYS_SHARE="${SKYVIEW_VNC_ALWAYS_SHARE:-false}"
SKYVIEW_VNC_LOCALHOST_ONLY="${SKYVIEW_VNC_LOCALHOST_ONLY:-false}"

# ============================================================================
# Installation Functions
# ============================================================================

# Install TigerVNC
install_vnc() {
    log_info "Installing TigerVNC..."

    local packages
    packages=$(get_packages_for_method "vnc")

    if [[ -z "$packages" ]]; then
        log_error "Could not determine VNC packages for OS: $SKYVIEW_OS_NAME"
        return 1
    fi

    if ! install_packages $packages; then
        log_error "Failed to install VNC packages"
        return 1
    fi

    log_info "TigerVNC installed successfully"
    return 0
}

# ============================================================================
# Configuration Functions
# ============================================================================

# Configure VNC for the current user
configure_vnc() {
    local user="${1:-$USER}"
    local display_num="${2:-0}"

    log_info "Configuring VNC for user: $user, display: $display_num"

    require_root || return 1

    # Set VNC display number
    SKYVIEW_VNC_DISPLAY=":${display_num}"
    SKYVIEW_VNC_PORT=$((5900 + display_num))

    # Get user home directory
    local user_home
    user_home=$(getent passwd "$user" | cut -d: -f6)
    if [[ -z "$user_home" ]]; then
        user_home="/home/$user"
    fi

    # Create VNC configuration directory
    local vnc_dir="${user_home}/.config/tigervnc"
    mkdir -p "$vnc_dir"
    chown "$user:$user" "$vnc_dir"

    # Create VNC config file
    local config_file="${vnc_dir/config}"
    create_vnc_config "$config_file"

    # Create VNC password if requested
    if [[ -n "$SKYVIEW_VNC_PASSWORD_FILE" ]]; then
        create_vnc_password "$user" "$SKYVIEW_VNC_PASSWORD_FILE"
    fi

    # Configure systemd user service
    configure_vnc_systemd_service "$user" "$display_num"

    log_info "VNC configuration complete for $user"
    return 0
}

# Create VNC configuration file
create_vnc_config() {
    local config_file="$1"

    cat > "$config_file" << EOF
# TigerVNC Configuration - Generated by SkyView Universal Remote Access
# Session settings
session=$(get_vnc_session_command)
geometry=${SKYVIEW_VNC_GEOMETRY}
depth=${SKYVIEW_VNC_DEPTH}

# Security settings
${SKYVIEW_VNC_LOCALHOST_ONLY:+localhost}
${SKYVIEW_VNC_ALWAYS_SHARE:+alwaysshared}

# Performance settings
${SKYVIEW_VNC_ALWAYS_SHARE:-#}shared
${SKYVIEW_VNC_LOCALHOST_ONLY:-#}localhost

# Security type (uncomment desired)
# securitytypes=vncauth,tlsvnc
# securitytypes=tlsvnc
# securitytypes=x509vnc
EOF

    # Apply security type
    case "$SKYVIEW_VNC_SECURITY_TYPE" in
        TLSVnc)
            echo "securitytypes=tlsvnc" >> "$config_file"
            ;;
        X509Vnc)
            echo "securitytypes=x509vnc" >> "$config_file"
            echo "X509Cert=${SKYVIEW_VNC_CERT_FILE:-/etc/tigervnc/cert.pem}" >> "$config_file"
            echo "X509Key=${SKYVIEW_VNC_KEY_FILE:-/etc/tigervnc/key.pem}" >> "$config_file"
            ;;
        None)
            echo "securitytypes=none" >> "$config_file"
            log_warn "VNC security disabled - not recommended for production!"
            ;;
        *)
            echo "securitytypes=vncauth,tlsvnc" >> "$config_file"
            ;;
    esac

    chmod 600 "$config_file"
    log_debug "Created VNC config: $config_file"
}

# Get the appropriate session command for VNC
get_vnc_session_command() {
    local de_lower
    de_lower=$(lowercase "$SKYVIEW_DE")

    # Check XDG session first
    if [[ -n "$DESKTOP_SESSION" ]]; then
        local desktop_file="/usr/share/xsessions/${DESKTOP_SESSION}.desktop"
        if [[ -f "$desktop_file" ]]; then
            local session_cmd
            session_cmd=$(grep -oP 'Exec=\K.*' "$desktop_file" 2>/dev/null | head -1)
            if [[ -n "$session_cmd" ]]; then
                basename "$session_cmd"
                return
            fi
        fi
    fi

    # Fallback to DE-specific defaults
    case "$de_lower" in
        *"kde"*|*"plasma"*) echo "startplasma-x11" ;;
        *"gnome"*) echo "gnome-session" ;;
        *"xfce"*) echo "xfce4-session" ;;
        *"cinnamon"*) echo "cinnamon-session" ;;
        *"mate"*) echo "mate-session" ;;
        *"lxqt"*) echo "lxqt-session" ;;
        *"lxde"*) echo "lxsession" ;;
        *"budgie"*) echo "budgie-session" ;;
        *"deepin"*) echo "deepin-session" ;;
        *) echo "xfce4-session" ;;  # XFCE is most compatible fallback
    esac
}

# Create VNC password file
create_vnc_password() {
    local user="$1"
    local password_file="$2"

    log_info "Creating VNC password for user: $user"

    # Get user home directory
    local user_home
    user_home=$(getent passwd "$user" | cut -d: -f6)
    local vnc_passwd_file="${user_home}/.config/tigervnc/passwd"

    # Create password using vncpasswd
    if command -v vncpasswd &>/dev/null; then
        if [[ -n "$SUDO_USER" ]]; then
            # Running as root, create password non-interactively
            echo "$password_file" | vncpasswd -f > "$vnc_passwd_file" 2>/dev/null || \
            sudo -u "$user" vncpasswd -f <<< "$password_file" > "$vnc_passwd_file" 2>/dev/null
        else
            vncpasswd -f <<< "$password_file" > "$vnc_passwd_file"
        fi

        if [[ -f "$vnc_passwd_file" ]]; then
            chmod 600 "$vnc_passwd_file"
            chown "$user:$user" "$vnc_passwd_file"
            log_info "VNC password created successfully"
            return 0
        fi
    else
        log_warn "vncpasswd command not found - cannot create password"
    fi

    return 1
}

# Configure systemd user service for VNC
configure_vnc_systemd_service() {
    local user="$1"
    local display_num="$2"

    # Get user home directory
    local user_home
    user_home=$(getent passwd "$user" | cut -d: -f6)
    local service_dir="${user_home}/.config/systemd/user"
    local service_file="${service_dir}/skyview-vnc.service"

    mkdir -p "$service_dir"

    cat > "$service_file" << EOF
[Unit]
Description=SkyView VNC Server
After=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/bin/vncserver :${display_num} -geometry ${SKYVIEW_VNC_GEOMETRY} -depth ${SKYVIEW_VNC_DEPTH} -localhost=${SKYVIEW_VNC_LOCALHOST_ONLY}
ExecStop=/usr/bin/vncserver -kill :${display_num}
Restart=on-failure
RestartSec=5
Environment=HOME=${user_home}

[Install]
WantedBy=default.target
EOF

    chown -R "$user:$user" "$service_dir"

    if command -v systemctl &>/dev/null; then
        sudo -u "$user" systemctl --user daemon-reload 2>/dev/null || true
        sudo -u "$user" systemctl --user enable skyview-vnc.service 2>/dev/null || true
    fi

    log_debug "Created systemd service: $service_file"
}

# Configure x0vncserver for sharing existing display
configure_x0vnc() {
    local user="${1:-$USER}"

    log_info "Configuring x0vncserver for display sharing..."

    require_root || return 1

    # Get user home directory
    local user_home
    user_home=$(getent passwd "$user" | cut -d: -f6)
    local service_dir="${user_home}/.config/systemd/user"
    local service_file="${service_dir}/skyview-x0vnc.service"

    mkdir -p "$service_dir"

    # Determine display number
    local display_num="0"
    if [[ -n "$DISPLAY" ]]; then
        display_num=$(echo "$DISPLAY" | grep -oP ':\K[0-9]+' | head -1)
    fi

    # Get password file
    local passwd_file="${user_home}/.config/tigervnc/passwd"
    local passwd_arg=""
    if [[ -f "$passwd_file" ]]; then
        passwd_arg="-rfbauth $passwd_file"
    fi

    # Get X authority
    local xauthority="${XAUTHORITY:-${user_home}/.Xauthority}"

    cat > "$service_file" << EOF
[Unit]
Description=SkyView X0VNC Server (Display Sharing)
After=graphical-session.target display-manager.service
Wants=display-manager.service

[Service]
Type=simple
ExecStart=/usr/bin/x0vncserver -display :${display_num} ${passwd_arg} -Shared -forever -PollForchesarOn
Restart=on-failure
RestartSec=5
Environment=HOME=${user_home} XAUTHORITY=${xauthority}
User=${user}

[Install]
WantedBy=multi-user.target
EOF

    chown -R "$user:$user" "$service_dir"

    if command -v systemctl &>/dev/null; then
        systemctl daemon-reload
        systemctl enable skyview-x0vnc.service 2>/dev/null || true
    fi

    log_info "x0vncserver configured for display :$display_num"
    return 0
}

# ============================================================================
# Service Management Functions
# ============================================================================

# Start VNC server
start_vnc() {
    local display_num="${1:-0}"

    log_info "Starting VNC server on display :$display_num..."

    if ! command -v vncserver &>/dev/null; then
        log_error "vncserver command not found"
        return 1
    fi

    # Check if already running
    if pgrep -f "vncserver :${display_num}" &>/dev/null; then
        log_warn "VNC server already running on display :$display_num"
        return 0
    fi

    # Start VNC server
    vncserver ":${display_num}" -geometry "$SKYVIEW_VNC_GEOMETRY" -depth "$SKYVIEW_VNC_DEPTH" -localhost="$SKYVIEW_VNC_LOCALHOST_ONLY" 2>&1 | tee /tmp/vncstart.log

    # Check if started successfully
    sleep 2
    if pgrep -f "vncserver :${display_num}" &>/dev/null; then
        log_info "VNC server started successfully on display :$display_num (port $((5900 + display_num)))"
        return 0
    else
        log_error "Failed to start VNC server"
        cat /tmp/vncstart.log
        return 1
    fi
}

# Stop VNC server
stop_vnc() {
    local display_num="${1:-0}"

    log_info "Stopping VNC server on display :$display_num..."

    if ! command -v vncserver &>/dev/null; then
        return 0
    fi

    vncserver -kill ":${display_num}" 2>/dev/null || true

    # Wait for cleanup
    sleep 1

    if pgrep -f "vncserver :${display_num}" &>/dev/null; then
        log_warn "VNC server may still be running"
        return 1
    fi

    log_info "VNC server stopped"
    return 0
}

# Start systemd user service
start_vnc_service() {
    local user="${1:-$USER}"

    log_info "Starting VNC user service for $user..."

    if command -v systemctl &>/dev/null; then
        sudo -u "$user" systemctl --user start skyview-vnc.service 2>/dev/null || \
        systemctl start "skyview-vnc@${user}.service" 2>/dev/null
    fi
}

# Stop VNC user service
stop_vnc_service() {
    local user="${1:-$USER}"

    log_info "Stopping VNC user service for $user..."

    if command -v systemctl &>/dev/null; then
        sudo -u "$user" systemctl --user stop skyview-vnc.service 2>/dev/null || \
        systemctl stop "skyview-vnc@${user}.service" 2>/dev/null
    fi
}

# ============================================================================
# Verification Functions
# ============================================================================

# Verify VNC configuration
verify_vnc() {
    log_info "Verifying VNC configuration..."

    local errors=0

    # Check if VNC server is installed
    if ! command -v vncserver &>/dev/null; then
        log_error "TigerVNC is not installed"
        ((errors++))
    fi

    # Check VNC password file permissions
    local passwd_file="${HOME}/.config/tigervnc/passwd"
    if [[ -f "$passwd_file" ]]; then
        local perms
        perms=$(stat -c %a "$passwd_file" 2>/dev/null)
        if [[ "$perms" != "600" ]]; then
            log_warn "VNC password file has incorrect permissions: $perms (should be 600)"
        else
            log_info "VNC password file permissions OK"
        fi
    fi

    # Check if VNC port is listening
    if is_port_open "localhost" "$SKYVIEW_VNC_PORT"; then
        log_info "VNC port $SKYVIEW_VNC_PORT is listening"
    else
        log_warn "VNC port $SKYVIEW_VNC_PORT is not listening"
    fi

    # Check for running VNC servers
    local vnc_pids
    vnc_pids=$(pgrep -f "vncserver" 2>/dev/null)
    if [[ -n "$vnc_pids" ]]; then
        log_info "VNC servers running (PIDs: $vnc_pids)"
    else
        log_info "No VNC servers currently running"
    fi

    return $errors
}

# ============================================================================
# Utility Functions
# ============================================================================

# Get VNC status
get_vnc_status() {
    local display_num="${1:-0}"
    local port=$((5900 + display_num))

    if is_port_open "localhost" "$port"; then
        echo "VNC :$display_num - listening on port $port"
    else
        echo "VNC :$display_num - not running"
    fi
}

# List running VNC servers
list_vnc_servers() {
    echo "Running VNC servers:"
    pgrep -af "vncserver" 2>/dev/null || echo "  None"
}

# Print VNC configuration summary
print_vnc_summary() {
    print_header "VNC Configuration"

    cat << EOF
VNC Display:      $SKYVIEW_VNC_DISPLAY
VNC Port:         $SKYVIEW_VNC_PORT
Geometry:         $SKYVIEW_VNC_GEOMETRY
Depth:            $SKYVIEW_VNC_DEPTH
Security Type:    $SKYVIEW_VNC_SECURITY_TYPE
Localhost Only:   $SKYVIEW_VNC_LOCALHOST_ONLY
Always Share:     $SKYVIEW_VNC_ALWAYS_SHARE

$(list_vnc_servers)
EOF
}
